

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thanh
 */
public class BT232 extends javax.swing.JFrame {

    /**
     * Creates new form BT232
     */
    public BT232() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filename = new javax.swing.JTextField();
        btnxuly = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAre = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhap ten tap tin");

        btnxuly.setText("Xu ly");
        btnxuly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxulyActionPerformed(evt);
            }
        });

        textAre.setColumns(20);
        textAre.setRows(5);
        jScrollPane1.setViewportView(textAre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnxuly)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxuly))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnxulyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxulyActionPerformed
        // TODO add your handling code here:
        String fileName = filename.getText();
        try {
            int[] integers = createIntegerArrayFromFile("D:\\" + fileName);
            List<int[]> arrays = splitArray(integers);

            textAre.setText("Nội dung các mảng:\n");
            for (int i = 0; i < arrays.size(); i++) {
                textAre.append("Mảng " + (i + 1) + ": " + arrayToString(arrays.get(i)) + "\n");
            }

            writeToFile(arrays);
        } catch (IOException ex) {
            textAre.setText("Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnxulyActionPerformed

     public static int[] createIntegerArrayFromFile(String fileName) throws IOException {
        BufferedReader fileReader = new BufferedReader(new FileReader(fileName));
        List<Integer> integerList = new ArrayList<>();

        String line;
        while ((line = fileReader.readLine()) != null) {
            int number = Integer.parseInt(line);
            integerList.add(number);
        }

        fileReader.close();

        // Chuyển List<Integer> thành mảng int[]
        return integerList.stream().mapToInt(Integer::intValue).toArray();
    }

    // Bước 3: Tách mảng thành các đoạn
    public static List<int[]> splitArray(int[] integers) {
        List<int[]> arrays = new ArrayList<>();
        int startIndex = 0;

        while (startIndex < integers.length) {
            int endIndex = Math.min(startIndex + 100, integers.length);
            int[] subArray = new int[endIndex - startIndex];
            System.arraycopy(integers, startIndex, subArray, 0, endIndex - startIndex);
            arrays.add(subArray);
            startIndex = endIndex;
        }

        return arrays;
    }

    // Chuyển mảng thành chuỗi
    public static String arrayToString(int[] array) {
        StringBuilder sb = new StringBuilder();
        sb.append("[");
        for (int i = 0; i < array.length; i++) {
            sb.append(array[i]);
            if (i < array.length - 1) {
                sb.append(", ");
            }
        }
        sb.append("]");
        return sb.toString();
    }

    // Bước 5: Ghi nội dung các mảng vào tập tin "Mang.txt"
    public static void writeToFile(List<int[]> arrays) throws IOException {
        BufferedWriter writer = new BufferedWriter(new FileWriter("D:\\Mang.txt")); // Lưu tập tin trong ổ D

        for (int[] array : arrays) {
            for (int i = 0; i < array.length; i++) {
                writer.write(String.valueOf(array[i]));
                if (i < array.length - 1) {
                    writer.newLine();
                }
            }
        }

        writer.close();
        System.out.println("Đã ghi thành công vào tập tin Mang.txt");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BT232.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BT232.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BT232.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BT232.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BT232().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnxuly;
    private javax.swing.JTextField filename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAre;
    // End of variables declaration//GEN-END:variables
}
